---
title: "Decision tree for activity classification"
author: "Fluve Vandelli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(conflicted)
conflicts_prefer(dplyr::select())

knitr::opts_chunk$set(warning=FALSE,
                      message=FALSE,
                      tidy.opts=list(width.cutoff = 60),
                      tidy = TRUE)
knitr::opts_knit$set(global.par=TRUE)

# built-in output hook
hook_output <- knitr::knit_hooks$get("output")
# custom chunk option output.lines to truncate text output
knitr::knit_hooks$set(output = function(x, options) {
  n <- options$output.lines
  if (!is.null(n)) {
      x <- xfun::split_lines(x)
      if(length(x) > n) {
          top <- head(x, n)
          bot <- tail(x, n)
          x <- c(top, "\n....\n", bot)
      }
      x <- paste(x, collapse="\n")
  }
  hook_output(x, options)
})
```



```{r first tree}
library(tree)
library(rpart)
library(rpart.plot)
library(tidyverse)
x <- as_tibble(WeNeteventsdata)

tree_model <- rpart(weekday ~ ., data = x, method = "class")
```



```{r pressure, echo=FALSE}
rpart.plot(tree_model, type = 0, extra = 6, under = TRUE, cex = 0.4, box.palette = "auto")

```
